// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/MyService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace MyGrpc {
  public static partial class MyService
  {
    static readonly string __ServiceName = "MyGrpc.MyService";

    static readonly grpc::Marshaller<global::MyGrpc.Request> __Marshaller_MyGrpc_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MyGrpc.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MyGrpc.NameAndSurname> __Marshaller_MyGrpc_NameAndSurname = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MyGrpc.NameAndSurname.Parser.ParseFrom);

    static readonly grpc::Method<global::MyGrpc.Request, global::MyGrpc.NameAndSurname> __Method_Search = new grpc::Method<global::MyGrpc.Request, global::MyGrpc.NameAndSurname>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Search",
        __Marshaller_MyGrpc_Request,
        __Marshaller_MyGrpc_NameAndSurname);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MyGrpc.MyServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MyService</summary>
    public abstract partial class MyServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::MyGrpc.NameAndSurname> Search(global::MyGrpc.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MyService</summary>
    public partial class MyServiceClient : grpc::ClientBase<MyServiceClient>
    {
      /// <summary>Creates a new client for MyService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MyServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MyService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MyServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MyServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MyServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::MyGrpc.NameAndSurname Search(global::MyGrpc.Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Search(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MyGrpc.NameAndSurname Search(global::MyGrpc.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Search, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MyGrpc.NameAndSurname> SearchAsync(global::MyGrpc.Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MyGrpc.NameAndSurname> SearchAsync(global::MyGrpc.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Search, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MyServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MyServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MyServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Search, serviceImpl.Search).Build();
    }

  }
}
#endregion
