# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import MyService_pb2 as proto_dot_MyService__pb2


class MyServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Search = channel.unary_unary(
        '/MyGrpc.MyService/Search',
        request_serializer=proto_dot_MyService__pb2.Request.SerializeToString,
        response_deserializer=proto_dot_MyService__pb2.NameAndSurname.FromString,
        )


class MyServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MyServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=proto_dot_MyService__pb2.Request.FromString,
          response_serializer=proto_dot_MyService__pb2.NameAndSurname.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MyGrpc.MyService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
